language: elixir

sudo: false

elixir:
  - 1.2.6

otp_release:
  - 18.1

addons:
  hosts:
    - db

env: MIX_ENV=test

script:
  - mix coveralls.travis

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on: master
  run:
    - mix ecto.migrate

notifications:
  email: false
