language: elixir

sudo: false

elixir:
  - 1.3.2

otp_release:
  - 19.0

addons:
  hosts:
    - db

env: MIX_ENV=test

script:
  - mix coveralls.travis

deploy:
  provider: heroku
  app: elixir-lang-moscow
  api_key: $HEROKU_API_KEY
  on: master

notifications:
  email: false
