language: elixir

sudo: false

elixir:
  - 1.3.2

otp_release:
  - 19.0

addons:
  hosts:
    - db

env: MIX_ENV=test

install:
  - npm install -g yarn
  - yarn install  # yarn is the default package manager

script:
  - mix coveralls.travis  # running ExUnit and pushing coverage
  - mix credo --only warning,refactor,consistency  # linting elixir
  - npm run lint  # linting js and scss

deploy:
  provider: heroku
  app: elixir-lang-moscow
  api_key: $HEROKU_API_KEY
  on: master

notifications:
  email: false
